### ISSUE TITLE
Unable to downgrade when newer syntax is present in autoload.files of some vendor package

### ISSUE THREAD

**Issue by janedbal** [ondrejmirtes/simple-downgrader#5]
If any package uses composer's `autoload.files` section, those files get [required immediately by composer](https://getcomposer.org/doc/04-schema.md#files). 

So if you run simple-downgrader on old PHP and there is a newer PHP syntax within those files, PHP fatal error is emitted. See [example failure](https://github.com/phpstan/phpstan-src/actions/runs/8019787823/job/21908275757?pr=2936#step:5:10) which runs PHP 7.3 and fails on [this line in symfony/string](https://github.com/symfony/string/blob/v6.4.3/Resources/functions.php#L34). Related [PR](https://github.com/phpstan/phpstan-src/pull/2936).

```
vendor/bin/simple-downgrade downgrade -c build/downgrade.php 7.3
PHP Parse error:  syntax error, unexpected '=' in /home/runner/work/phpstan-src/phpstan-src/vendor/symfony/string/Resources/functions.php on line 34
```

I'm not sure there is any easy mitigation of that. But I kinda expected that simple-downgrader dont need to be executed with old PHP versions.

**Comment by ondrejmirtes** [comment]
I don't plan to downgrade dependencies with simple-downgrader. So PHPStan should always use 7.2+ dependencies in `require`/`require-dev`.

**Comment by janedbal** [comment]
This is not about downgrading dependencies. If any of your dependencies does `require file_with_new_syntax.php` (including transitive dependencies!), your downgrader breaks. And this happens via `autoload.files` in `composer.json`.

Yes, you can bypass that by listing such dependency in phpstan's composer while pinning some old version that does not do that. But that way you are adding unused dependencies to phpstan-src just to avoid issues with simple-downgrader.

**Comment by ondrejmirtes** [comment]
>  If any of your dependencies does require file_with_new_syntax.php

But that means the dependency does not support PHP 7.2+ and shouldn't be present in this version at all.

**Comment by janedbal** [comment]
> But that means the dependency does not support PHP 7.2+ and shouldn't be present in this version at all.

How do you guard that for the number of dependencies you use in phpstan? PHPStan could use `config.platform.php` to state 7.2 (which would guarantee it), but that is not happening.

**Comment by ondrejmirtes** [comment]
By testing PHPStan in CI on all versions from 7.2+.

There is some reason for the current value of `config.platform.php`. I tried to change it but some other stuff didn't work.

For example I use a version of PHPUnit which declares requirement for `>= 7.3` but thanks to some coincidence it works on 7.2.

At the same time I can't use `8.3` there because some dependencies officially support only `<= 8.2`.

I hope to clean this up a bit in PHPStan 2.0 which will require PHP 7.4+.

**Comment by janedbal** [comment]
Ok, I get it. 

So I just need to keep some unused dependencies listed in composer.json in https://github.com/phpstan/phpstan-src/pull/2936 to ensure those are pinned to support PHP 7.2.
