### ISSUE TITLE
Why not using Rector?

### ISSUE THREAD

**Issue by ghost** [ondrejmirtes/simple-downgrader#6]
HI, this is just a question. Isn't Rector a dedicated tool for (down|up)grading code to the given PHP version?

**Comment by ondrejmirtes** [comment]
I used Rector previously but since Rector is based on PHPStan, it sometimes broke.

Simple-downgrader is also much faster at what we need it to do.

This also unties our hands when we'll be soon working on PHPStan 2.0 with PHP-Parser 5, which will break Rector for sure.
